### PR TITLE
Support ssl for pdo_mysql and mysqli

### LINKED ISSUE #1508: Typecho连接云数据库出错
### 1. 该问题的重现步骤是什么？
Typecho安装阶段连接云数据库出错,云数据库提供商为planetscale，查看操作说明是需要开启SSL才能正常登陆，然后谷歌相关结果只有Wordpress，请问Typecho怎么连接开启了SSL的数据库，或者需要修改哪里？
微信截图_20221024175521

### 2. 你期待的结果是什么？实际看到的又是什么？
正常连接云数据库
### 3. 问题出现的环境

- 操作系统版本：Debian11
- Apache/NGINX 版本：NGINX1.22
- 数据库版本：8.0
- PHP 版本：8.17
- Typecho 版本：1.20
- 浏览器版本：Edge 106

[//]: # (如有图片请附上截图)
微信截图_20221024175117

### PR DESCRIPTION
**Pull request by sy-records**
支持了一下简版的ssl，测试planetscale通过。

腾讯云的云db，开启ssl以后连接使用证书，需要关闭验证，那开启ssl意义好像就没了 😅

```
Peer certificate CN=`TencentDB ROOT SERVER-CA' did not match expected CN...
```

Close #1508

### CODE REVIEW

**Comment by AncientCatz** [comment]
Does it really work?

**Comment by sy-records** [comment]
I've tested planetscale and Tencent Cloud

**Comment by hurui200320** [comment]
Tested with Linode's managed database, and it's working.

@joyqi Can we have this patch in 1.2.1?

**Comment by joyqi** [comment]
@sy-records @hurui200320 I've made some enhancements for this issue, and I think we should validate it for both `Pdo_Mysql` and `Mysqli`.

**Comment by hurui200320** [comment]
I tested the `Pdo_Mysql`. Today I was migrating from my local MySQL to Linode's managed MySQL and eventually find this pr. I applied the changes to the latest 1.2.1-rc code and it's working properly. 

(Yes, I did that in production env, LOL)

**Comment by sy-records** [comment]
@joyqi I tested it and it's ok for me

**Pull request merged**
